/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SalesOrdersRouteImport } from './routes/sales-orders'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as ManufacturingRouteImport } from './routes/manufacturing'
import { Route as IndexRouteImport } from './routes/index'

const SalesOrdersRoute = SalesOrdersRouteImport.update({
  id: '/sales-orders',
  path: '/sales-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ManufacturingRoute = ManufacturingRouteImport.update({
  id: '/manufacturing',
  path: '/manufacturing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/manufacturing': typeof ManufacturingRoute
  '/products': typeof ProductsRoute
  '/sales-orders': typeof SalesOrdersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manufacturing': typeof ManufacturingRoute
  '/products': typeof ProductsRoute
  '/sales-orders': typeof SalesOrdersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/manufacturing': typeof ManufacturingRoute
  '/products': typeof ProductsRoute
  '/sales-orders': typeof SalesOrdersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/manufacturing' | '/products' | '/sales-orders'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/manufacturing' | '/products' | '/sales-orders'
  id: '__root__' | '/' | '/manufacturing' | '/products' | '/sales-orders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ManufacturingRoute: typeof ManufacturingRoute
  ProductsRoute: typeof ProductsRoute
  SalesOrdersRoute: typeof SalesOrdersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sales-orders': {
      id: '/sales-orders'
      path: '/sales-orders'
      fullPath: '/sales-orders'
      preLoaderRoute: typeof SalesOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manufacturing': {
      id: '/manufacturing'
      path: '/manufacturing'
      fullPath: '/manufacturing'
      preLoaderRoute: typeof ManufacturingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManufacturingRoute: ManufacturingRoute,
  ProductsRoute: ProductsRoute,
  SalesOrdersRoute: SalesOrdersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
